branches:
  only:
  - master
  - playground

language: java

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "martinschneider-github"
    token:
      secure: "Jy11hm6mSF1KkMl00MxmkWcI9v5MN5CFiC5l3ze3dS/Uss8LO12I84/KBAiVPwdNA2KQLcuXePT2G/imvMhnvQIkhFvI0JsQXYGQFLV/ubsOICE1HQ30MpHwclUPrVfRc/b9rVz0Fdt2iiaIhrSShdVepQB9o4GQdtud4S8/CDMs6S6MdOUs/KWzqrfMoM19iXH72TvOc9OHZVqMPpKGQ9PY8zCgb1kvuOVmBBNEXmtyT5aRf9wt2BKMbWTy84LaLV5ITVK2VxyRPoDPXRm/AjjT9csEnx/bIKJ5nTwBvSxYYf/EUnKO6Bn333A4m60FTt6GkapLE9PFhOTldy/8ovkKaNw+M1oNmhPtUmPSqZrRaIcDFi53/iayDkdvkTAcas7nm0S8cXnRvDWmSEntOz+JqTamgoyPhyBq9a3UBnuaZ/w5imcbikSo/zJo2wqocs1QjsvlX4UYW1mk9AOyd+KbFgzRxb21uUJcAYShxNEcvMr+khI90+hExq+2r0ccIKS2GpLWQMjbZfKcgNNB51n6D31BKcRx5MxYLSjmw2QCBn5ONBq9yJOp2p+j0I3GxPNN1KzUPqoCQNUAxpJK3q2Nvhe0/xyV+eo1B71EDYiCZU+v/bUN5x+KV6cSDfwtCw8+tZ25Ur57VU0TlwKk80ZeA4U4Zmz6eh0cwXYDu/w="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dchromeoptions.args=--no-sandbox
