name: Integration Test
on: [push]

jobs:
  build:
    runs-on: macos-11
    name: Android test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          architecture: x64
      - name: Run Android test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: chmod +x ./scripts/android-integration-test.sh && ./scripts/android-integration-test.sh
