name: Java CI

on: [push]

jobs:
  build:  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '10', '11', '12', '13', '14', '15' ]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.home=/usr/share/apache-maven-3.8.1
